### PR TITLE
[FW] c1

### PR DESCRIPTION
**Pull request by xmo-odoo**
Forward-Port-Of: odoo-mergebot-testing-org/ignore_proj_xS_VvgZd#1

### CODE REVIEW

**Comment by xmo-odoo** [comment]
[Pull request status dashboard](http://localhost:8069/odoo-mergebot-testing-org/ignore_proj_xS_VvgZd/pull/2).

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer cherrypicking of pull request odoo-mergebot-testing-org/ignore_proj_xS_VvgZd#1 failed.

* 6c20ff7fba1e240d0d186e4e8adce531a144ec0f <- on this commit
* 2dc653b4b40559e7096729e95770622c18467c0b

stdout:
```
Auto-merging g
CONFLICT (add/add): Merge conflict in g

```

stderr:
```
11:43:35.933134 git.c:460               trace: built-in: git cherry-pick 6c20ff7fba1e240d0d186e4e8adce531a144ec0f
error: could not apply 6c20ff7... c0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by odoomergebotsacrifice-reviewer** [comment]
hansen r+

**Comment by xmo-odoo** [comment]
@xmo-odoo @odoomergebotsacrifice-reviewer unable to stage: All commits must have author and committer email, missing email on 8261a1144eb21930e8a95c44d3b0b16d5a751266 indicates the authorship is most likely incorrect.

**Pull request closed without merging**
